platform :ios, '11.2'

source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

inhibit_all_warnings!

target 'DevKit_Example' do
  pod 'DevKit', :path => '../'

  target 'DevKit_Tests' do
    inherit! :search_paths
  end

end
