platform :ios, '11.2'

source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

inhibit_all_warnings!

target 'DevKit_Example' do

  pod 'DevKit', :path => '../', :subspecs => ['TransitioningNavigationView']
  pod 'DevKit', :path => '../', :subspecs => ['CalendarPermissionsValidator']

  pod 'DevKit', :path => '../', :subspecs => ['Protocols/KeyboardObserver']
  pod 'DevKit', :path => '../', :subspecs => ['Protocols/ReusableCell']


  target 'DevKit_Tests' do
    inherit! :search_paths
  end

end
