# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

use_frameworks!

target 'DevKit' do

  # https://github.com/PureLayout/PureLayout/releases
  pod 'PureLayout', '3.0.2'

  # https://github.com/prolificinteractive/Marker/releases
  pod 'Marker', '1.1.0'

  # https://github.com/prolificinteractive/Moulinette
  pod 'Moulinette', '0.1.0'

  # https://github.com/kishikawakatsumi/KeychainAccess
  pod 'KeychainAccess', '3.1.0'

  target 'DevKitTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DevKitUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
